version: '3'

services:
  samples:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/usr/src/app
    environment:
      - PORT=3000
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DATABASE_NAME=homeworks
      - NODE_ENV=local
    ports:
      - 3000:3000
      - 9222:9222
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017
    command: mongod
    restart: always

volumes:
  mongodata: